CREATE DATABASE QLSV5
GO

USE QLSV5
GO

CREATE TABLE SINHVIEN(
MaSV NVARCHAR(10) NOT NULL,
TenSV NVARCHAR(30) NOT NULL,
QUE NVARCHAR(20),
CONSTRAINT pk_SINHVIEN PRIMARY KEY(MaSV)
)
GO

CREATE TABLE MON(
MaMH NVARCHAR(10) NOT NULL PRIMARY KEY,
TenMH NVARCHAR(20) NOT NULL,
Sotc INT DEFAULT(3) CONSTRAINT chk_sotc CHECK(Sotc>=2 AND Sotc<=5),
CONSTRAINT UNIQUE_MON UNIQUE(TenMH)
)
GO

CREATE TABLE KQ(
MaSV NVARCHAR(10) NOT NULL,
MaMH NVARCHAR(10) NOT NULL,
Diem INT CONSTRAINT chk_diem CHECK(Diem>=0 AND Diem<=10),
CONSTRAINT pk_KQ PRIMARY KEY(MaSV, MaMH),
CONSTRAINT fk_SINHVIEN_kq FOREIGN KEY(MaSV) REFERENCES SINHVIEN(MaSV),
CONSTRAINT fk_MON_kq FOREIGN KEY(MaMH) REFERENCES MON(MaMH)
)
GO

INSERT INTO SINHVIEN VALUES('AV0807005', N'Dương Thị Hồng Vân', N'Hà Nam')
INSERT INTO SINHVIEN VALUES('AV0807006', N'Phan Thị Lan Anh', N'Thái Bình')
INSERT INTO SINHVIEN VALUES('AV0807007', N'Mai Thị Ánh Tuyết', N'Nam Định')

INSERT INTO MON VALUES('S001', 'SQL', '4')
INSERT INTO MON VALUES('S002', 'Java Simplefield', '3')
INSERT INTO MON VALUES('S003', 'Active Server Page', '4')

INSERT INTO KQ VALUES('AV0807005', 'S001','8')
INSERT INTO KQ VALUES('AV0807006', 'S002', '6')
INSERT INTO KQ VALUES('AV0807007', 'S001', '10')
INSERT INTO KQ VALUES('AV0807005', 'S003', '7')
INSERT INTO KQ VALUES('AV0807007', 'S003','9')
INSERT INTO KQ VALUES('AV0807006', 'S001','8')

SELECT * FROM SinhVien
SELECT * FROM MON
SELECT* FROM KQ






