CREATE DATABASE QLBH7
GO

USE QLBH7
GO

CREATE TABLE CONGTY(
MaCT NCHAR(10) NOT NULL PRIMARY KEY,
TenCT NVARCHAR(20) NOT NULL,
TrangThai NCHAR(10), 
ThanhPho NVARCHAR(20)
)
GO

CREATE TABLE SANPHAM(
MaSP NCHAR(10) NOT NULL PRIMARY KEY,
TenSP NVARCHAR(15) NOT NULL,
MauSac NCHAR(10) DEFAULT N'Đỏ',
Gia MONEY,
SoLuongCo INT,
CONSTRAINT unique_SP UNIQUE(TenSP)
)
GO

CREATE TABLE CUNGUNG(
MaCT NCHAR(10) NOT NULL,
MaSP NCHAR(10) NOT NULL,
SoLuongBan INT CONSTRAINT chk_soluongban CHECK(SoLuongBan>0),
CONSTRAINT pk_CUNGUNG PRIMARY KEY(MaCT, MaSP),
CONSTRAINT fk_CONGTY_cu FOREIGN KEY(MaCT) REFERENCES CONGTY(MaCT),
CONSTRAINT fk_SANPHAM_cu FOREIGN KEY(MaSP) REFERENCES SANPHAM(MaSP)
)
GO


INSERT INTO CONGTY VALUES('AV0807005','Microsoft',N'hoạt động', N'Hà Nội')
INSERT INTO CONGTY VALUES('AV0807006','FPT',N'hoạt động', N'Phú Thọ')
INSERT INTO CONGTY VALUES('AV0807007', 'ITC',N'kết thúc', N'Bắc Kinh')

INSERT INTO SANPHAM VALUES('S001', 'Smartphone', N'Đỏ', '300', '200')
INSERT INTO SANPHAM VALUES('S002', 'Television', N'Đỏ', '100', '50' )
INSERT INTO SANPHAM VALUES('S003', 'frigde', N'Đỏ', '200', '100')


INSERT INTO CUNGUNG VALUES('AV0807005', 'S001','8')
INSERT INTO CUNGUNG VALUES('AV0807006', 'S002', '6')
INSERT INTO CUNGUNG VALUES('AV0807007', 'S001', '10')
INSERT INTO CUNGUNG VALUES('AV0807005', 'S003', '7')
INSERT INTO CUNGUNG VALUES('AV0807007', 'S003','9')
INSERT INTO CUNGUNG VALUES('AV0807006', 'S001','8')

SELECT * FROM CONGTY
SELECT * FROM SANPHAM
SELECT* FROM CUNGUNG





