use master
go
if (exists (select * from sysdatabases where name ='QLBH'))
drop database QLBH
go
create database QLBH
on primary (name='QLBH_dat', filename = 'E:\MYSQL\QLBH.mdf', size=2MB, maxsize=10MB, filegrowth=20%)
log on (name='QLBH_log', filename = 'E:\MYSQL\QLBH.ldf', size=1MB, maxsize=5MB, filegrowth=1MB)
go
use QLBH
go

-- TAO BANG NHACC
CREATE TABLE NHACC
(MANCC CHAR(3) PRIMARY KEY,
TENNCC NVARCHAR(100) NOT NULL,
DIACHI NVARCHAR(200) NOT NULL,
DIENTHOAI VARCHAR(20) NOT NULL DEFAULT('CHUA CO')
)
--TAO BANG DONDH
CREATE TABLE DONDH
(SODH CHAR(4) PRIMARY KEY,
NGAYDH DATETIME DEFAULT('GETDATE'),
MANCC CHAR(3),
CONSTRAINT FK FOREIGN KEY(MANCC) REFERENCES NHACC(MANCC) ON UPDATE CASCADE ON DELETE CASCADE
)

--TAO BANG PNHAP
CREATE TABLE PNHAP
(SOPN CHAR(4) PRIMARY KEY,
NGAYNHAP DATETIME,
SODH CHAR(4),
CONSTRAINT FK1 FOREIGN KEY(SODH) REFERENCES DONDH(SODH) ON UPDATE CASCADE ON DELETE CASCADE
)

--TAO BANG VATTU
CREATE TABLE VATTU
(MAVTU CHAR(4) PRIMARY KEY,
TENVTU NVARCHAR(100) NOT NULL,
DVTINH NVARCHAR(10) DEFAULT('0'),
PHANTRAM REAL CHECK(PHANTRAM BETWEEN 0 AND 100)
)

--TAO BANG CTPNHAP
CREATE TABLE CTPNHAP
(SOPN CHAR(4),
MAVTU CHAR(4),
SLNHAP INT CHECK(SLNHAP > 0),
DLNHAP MONEY CHECK(DLNHAP > 0),
CONSTRAINT PK PRIMARY KEY (SOPN, MAVTU),
CONSTRAINT FK2 FOREIGN KEY(MAVTU) REFERENCES VATTU(MAVTU) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK3 FOREIGN KEY(SOPN) REFERENCES PNHAP(SOPN) ON UPDATE CASCADE ON DELETE CASCADE
)

--TAO BANG TONKHO
CREATE TABLE TONKHO
(NAMTHANG CHAR(6) PRIMARY KEY,
MAVTU CHAR(4),
SLDAU INT CHECK(SLDAU >=0),
TONGSLN INT CHECK(TONGSLN >=0),
TONGSLX INT CHECK(TONGSLX >=0),
SLCUOI INT CHECK(SLCUOI >=0),
CONSTRAINT FK4 FOREIGN KEY(MAVTU) REFERENCES VATTU(MAVTU) ON UPDATE CASCADE ON DELETE CASCADE
)

--TAO BANG CTDONDH
CREATE TABLE CTDONDH
(SODH CHAR(4),
MAVTU CHAR(4),
SLDAT INT CHECK(SLDAT > 0),
CONSTRAINT PK1 PRIMARY KEY (SODH, MAVTU),
CONSTRAINT FK5 FOREIGN KEY(SODH) REFERENCES DONDH(SODH) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK6 FOREIGN KEY(MAVTU) REFERENCES VATTU(MAVTU) ON UPDATE CASCADE ON DELETE CASCADE
)

--TAO BANG PXUAT
CREATE TABLE PXUAT
(SOPX CHAR(4) PRIMARY KEY,
NGAYXUAT DATETIME,
TENKH NVARCHAR(100)
)

--TAO BANG CTPXUAT
CREATE TABLE CTPXUAT
(SOPX CHAR(4),
MAVTU CHAR(4),
SLXUAT INT CHECK(SLXUAT > 0),
DLXUAT MONEY CHECK(DLXUAT > 0),
CONSTRAINT PK2 PRIMARY KEY (SOPX, MAVTU),
CONSTRAINT FK7 FOREIGN KEY(MAVTU) REFERENCES VATTU(MAVTU) ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK8 FOREIGN KEY(SOPX) REFERENCES PXUAT(SOPX) ON UPDATE CASCADE ON DELETE CASCADE
)